<main class="content-wrapper">
    <section class="content-sec">
        <div class="box-content-layout">
            <div class="title-sec">
                <h1>PERFORMER VERIFICATION & AGREEMENT</h1>
            </div>
            <div class="box-content-widget">
                <div class="ovr-scrl-box" id="content-ltn">
                    <p>This electronic document is a legally binding and enforceable contract and agreement (referred to herein as this "Agreement") between you (referred to herein as "Performer/Studio" or "you") and ICF Technology, Inc. (referred to herein as "Streamate"). By providing your electronic signature below and all the required information and documents, you are agreeing to be bound by and acknowledging your complete acceptance of all the terms and conditions of this Agreement.</p>
                    <ol>
                        <li>
                            <p>Web Interface</p>
                            <p>Subject to the terms and conditions of this Agreement, Streamate agrees to provide Performer/Studio access to and use of a proprietary web interface to be utilized on the Streamate computer systems ("systems"). Performer/Studio understands and agrees this web interface is and will remain the exclusive property of Streamate, and that under no circumstances will Performer/Studio distribute, copy, duplicate or reverse engineer the Streamate web interface in any way, shape, form or methodology.</p>
                            <ul>
                                <li>
                                    <p>Revenue.</p>
                                    <p>Subject to the terms and conditions of this Agreement, Performer/Studio may use this web interface to generate revenue for live performances, and Performer/Studio agrees to provide content to Streamate, as provided below. Performer/Studio will have the right to set up pricing at your discretion, provided that Performer/Studio complies with the minimum price as determined by Streamate. Streamate agrees to pay Performer/Studio monies in the amount of the Performer/Studio percentage as specified by Streamate of all live chat sales generated by Performer/Studio via check, wire (US only), or payment to Paxum or other payment options offered based on the information and documents provided to Streamate by Performer/Studio. With respect to any payment made to Performer/Studio via payment to Paxum, once Streamate has forwarded payment to Paxum, then Streamate will be deemed to have satisfied all its obligations to make such payment to Performer/Studio.</p>
                                </li>
                                <li>
                                    <p>NO PROSTITUTION OR SEX TRAFFICKING.</p>
                                    <p>We strictly prohibit you from using our service or any of our websites in any way whatsoever to engage in, participate in, assist, support, or facilitate any act of prostitution, sex trafficking of children, or sex trafficking by force, fraud, or coercion. This includes but is not limited to you may not use our Service: (1) to exchange any personal contact information with one of our users or to have any communication with one of our users which would in any way result in any type of face-to-face meeting involving you and one of our users; or (2) to discuss in any way with one of our users any type of transaction whatsoever involving use of any other service or method of interfacing with one of our users, such as use of any other Internet based service or product. Any violation of these prohibitions will result in immediate cancellation of your account, you will be blocked from ever being a Performer or Studio on any of our websites in the future, and your payments will be withheld. We will cooperate fully with any criminal investigation by any police or other government criminal enforcement agency.</p>
                                    <p>If you are a Studio or model and you are engaging in, participating in, assisting, supporting, or facilitating any type of prostitution, sex trafficking of children, or sex trafficking by force, fraud, or coercion, you must immediately cease all such wrongful conduct.</p>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <p>Your Separate Business</p>
                            <p>At all times while using the Streamate web interface, Performer/Studio shall have your own business license, pay your own taxes, and take all other actions necessary and required to operate as your own separate and distinct business. Performer/Studio represents and warrants that Performer/Studio will obtain and keep current all business licenses as required by federal, state and local laws relating to you generating revenue under the terms of this Agreement. Performer/Studio is responsible for obtaining any and all registrations, certificates, and licenses and for satisfying all obligations related to Performer/Studio's payment of taxes under the applicable laws of any country, state or local government. Performer/Studio is also responsible for maintaining appropriate workers compensation coverage or insurance for you and any of your employees.</p>
                            <p>Performer/Studio shall not be deemed or treated as an employee of Streamate for any purpose. Nothing contained in this Agreement shall be deemed or construed by the parties to create the relationship of employer and employee, principal and agent, co-venturers, partners, or any other type of business association, other than as parties to this Agreement. Streamate will not pay or make any payments on behalf of or for the benefit of Performer/Studio related to Social Security, Medicare, FICA, VAT taxes, federal or country taxes, state taxes, local taxes, workers compensation, unemployment premiums or insurance, or any other payments. Performer/Studio shall have no claim against Streamate for any wages, vacation pay, sick leave, Social Security, workers compensation, unemployment benefits, or any other benefits of any kind. Additionally, Performer/Studio will not be eligible for any retirement benefits, 401(k) benefits, profit sharing benefits, bonuses, or any other types of benefits to be paid or owed by Streamate.</p>
                        </li>
                        <li>
                            <p>No Right To Control</p>
                            <p>As long as Performer/Studio satisfies the conditions stated herein for the use of the Streamate web interface, Performer/Studio shall be free to exercise Performer/Studio's own judgment, discretion and creativity as to the means, manner and details of giving performances while using the Streamate web interface. The parties agree Streamate does not have any control over or the right to control the means, manner or details Performer/Studio may use in giving performances while using the Streamate web interface to generate revenues under the terms of this Agreement.</p>
                        </li>
                        <li>
                            <p>Age Verification</p>
                            <p>Performer/Studio represents and warrants that Performer/Studio has reached the age of 18 (19 in Canada), and that the identification ("I.D.") provided to Streamate is valid and accurately reflects and represents the fact that Performer/Studio has reached the age of 18 (19 in Canada).</p>
                        </li>
                        <li>
                            <p>Term</p>
                            <p>This Agreement shall commence upon Performer/Studio's proper submission of this signed Agreement and all required information and documentation and Streamate's review and approval of Performer/Studio's submission. This Agreement shall remain enforceable until terminated by one of the parties. Performer/Studio will have the right to terminate this Agreement by providing written notice to Streamate. Streamate may terminate this Agreement and may cancel Performer/Studio's account at its complete sole discretion for any reason whatsoever, including but not limited to: (1) Performer/Studio's breach of or non-compliance with any term or condition of this Agreement; (2) Performer/Studio's acts or omissions constituting dishonesty, fraud, misrepresentation, theft or breach of confidentiality; (3) Performer/Studio's acts or omissions that impair Streamate's or any of Streamate's related entities' business, goodwill, or reputation; or (4) Performer/Studio's conviction of, or plea of no contest to, a crime constituting a felony or gross misdemeanor under local, state or federal law or involving fraud, dishonesty, or moral turpitude which adversely affects Streamate or any of its related entities.</p>
                            <p>In the case of termination of this Agreement, the parties agree to remit any monies owed to the other within a reasonable period of time, and Performer/Studio agrees to cease engaging in access to or any activity in any way involving the Streamate web interface or any Streamate website.</p>
                            <p>PERFORMER/STUDIO UNDERSTANDS AND AGREES THAT STREAMATE MAY SET OFF AGAINST ANY MONIES OWED TO PERFORMER/STUDIO ANY LIABILITY, DAMAGES, COSTS OR EXPENSES INCURRED BY STREAMATE ARISING FROM OR RELATING TO PERFORMER'S BREACH OR FAILURE TO PERFORM ANY TERM OR CONDITION OF THIS AGREEMENT.</p>
                        </li>
                        <li>
                            <P>Prohibited Uses Of Funds Paid By Streamate</P>
                            <P>Performer/Studio agrees that any funds or amounts paid by Streamate to Performer/Studio will not be used by Performer/Studio for any “Prohibited Use,” as such term is defined in this Agreement. For purposes of this Agreement, a “Prohibited Use” is defined as Performer/Studio using funds or amounts paid by Streamate, directly or indirectly, for any of the following purposes or uses:</P>
                            <ul>
                                <li>
                                    <P>To engage in any act of illegal money laundering, or to support or contribute to any person, organization, or other entity engaging in any act of illegal money laundering;</P>
                                </li>
                                <li>
                                    <P>To engage in any act of or planning of terrorism of any type, or to support or contribute to any person, organization, or other entity engaging in or planning any act of terrorism of any type;</P>
                                </li>
                                <li>
                                    <P>To engage in or support any type of war or armed conflict between countries or between groups or organizations; or</P>
                                </li>
                                <li>
                                    <P>To engage in any or to support in any way any illegal activity of any type, as determined by applicable laws.</P>
                                    <P>In the event that Streamate shall discover that Performer/Studio is using any funds or amounts paid by Streamate to Performer/Studio for any “Prohibited Use,” then Performer/Studio’s account with Streamate will be immediately terminated and Streamate will have no obligation to make any future payments to Performer/Studio.</P>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <p>Conditions For Use Of Web Interface</p>
                            <p>In order to use the Streamate web interface under the terms of this Agreement, Performer/Studio must satisfy the following conditions. Failure to satisfy any of these conditions may result in Streamate's termination of this Agreement and suspension or permanent closure of your account with Streamate.</p>
                            <ul>
                                <li>
                                    <p>NO SEX TRAFFICKING; NO SOLICITATION OF PERSONAL CONTACT WITH CUSTOMERS.</p>
                                    <p>Overall, and as emphasized in Paragraph A.2 above, it is illegal and strictly prohibited for you to engage in, participate in, assist, support, or facilitate any act of prostitution, sex trafficking of children, or sex trafficking by force, fraud, or coercion. This includes, without limitation, it is prohibited for you to exchange any personal contact information with any user, or for you to take any action to arrange any type of face-to-face meeting with a user. Also, it is prohibited for you to discuss with a user any transaction involving any other service or product, including but not limited to any other Internet based service. Accounts found to be involved in any of these activities will be terminated and payments will be withheld.</p>
                                </li>
                                <li>
                                    <p>PERFORMER/STUDIO ACCOUNTS.</p>
                                    <p>Your account with Streamate may only include performers who have properly registered and who are approved by Streamate to appear on your account. Accounts with performers who have not properly registered with Streamate or have not submitted all required and proper documentation will be closed permanently. If you are no longer using your account, your account must be closed. Inactive accounts will be closed after a specific amount of time and cannot be recovered.</p>
                                </li>
                                <li>
                                    <p>AGE DOCUMENTS MUST BE SUBMITTED FOR ALL PERFORMER/STUDIOS.</p>
                                    <p>By appearing live you are verifying that you have reached the age 18 (19 in Canada) and have submitted all proper documentation and age verification forms to perform on the website. Only individuals who have submitted proper documentation and have been approved to perform may appear on cam.</p>
                                </li>
                                <li>
                                    <p>NO BELOW THE WAIST NUDITY IN FREE CHAT.</p>
                                    <p>In order to prevent minors' exposure to below the waist nudity and adult material, no below the waist nudity is allowed in "free chat." Below the waist nudity is only allowed in age-verified areas, which are also known as "private" or "paid chat." Below the waist nudity in free areas will result in temporary suspension or permanent closing of your account.</p>
                                </li>
                                <li>
                                    <p>NO VIOLATION OF LAWS RE OBSCENITY OR MINORS.</p>
                                    <p>Performer/Studio shall not violate any local community standard of "obscenity" during any performance related to this Agreement, including but not limited to Performer/Studio shall not depict or describe any act of a sexual nature involving bestiality, necrophilia, coprophilia, urine, feces, vomit, blood, or others. Additionally, during any performance related to this Agreement, Performer/Studio shall not depict or describe any minor activity or act of a sexual nature involving persons under the age of 18 years (including but not limited to sex of any kind, simulated sex, sexual conduct, masturbation, bondage, domination, sadomasochism, or others).</p>
                                </li>
                                <li>
                                    <p>NO PROMOTION OF OTHER SITES.</p>
                                    <p>Promotion of any non-Streamate related website directly to Streamate members and affiliate site members is strictly prohibited. This includes but is not limited to by chat, by text, or by any other means. Violation of this condition will result in termination of this Agreement and the permanent termination of your account. Additionally, Streamate reserves the right to withhold payments to you if this condition is violated.</p>
                                </li>
                                <li>
                                    <p>NOT UNDER INFLUENCE OF ALCOHOL OR ILLEGAL DRUGS.</p>
                                    <p>While giving any performance or taking any other action related to this Agreement, Performer/Studio shall not be under the influence of alcohol or any illegal drug or controlled substance.</p>
                                </li>
                                <li>
                                    <p>NO ANIMALS OR FIREARMS ON CAM.</p>
                                    <p>While giving any performance, Performer/Studio is prohibited from having any animal appear on cam and from having any firearm or gun of any type appear on cam.</p>
                                </li>
                                <li>
                                    <p>NO FRAUDULENT ACTIVITY.</p>
                                    <p>While giving any performance or taking any other action related to this Agreement, Performer/Studio shall not engage in any type of fraudulent activity. Fraudulent activity is defined as any activity on the site that results in complaints or chargebacks, or is deemed inappropriate by Streamate's representatives. Streamate reserves the right to terminate any account at any time for any reason if fraud is suspected and to not make any related payments.</p>
                                </li>
                                <li>
                                    <p>IMAGE APPROVAL.</p>
                                    <p>Images submitted to Streamate for Performer/Studio's bio must be approved by Streamate. Images graphic in nature or containing "below the waist nudity" will not be approved. Streamate reserves the right to approve or reject any image submitted.</p>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <p>Other Websites</p>
                            <p>Performer/Studio has the right to work with other websites during the term of this Agreement and is not obligated to devote full-time efforts in generating revenues using the Streamate web interface. However, while in any way using the Streamate web interface, Performer/Studio is prohibited from engaging in any promotion of any non-Streamate website. Performer/Studio is allowed to own and operate a personal website; provided, that Performer/Studio shall not solicit Streamate customers or other Streamate Performer/Studios through use of the personal website. Performer/ Studio shall not release or give to any person or entity any email address or web page address of any Streamate customer or Streamate Performer/Studio without the prior written approval of Streamate in each instance.</p>
                        </li>
                        <li>
                        <li>
                            <p>Content</p>
                            <p>Performer/Studio will upload and transmit content in the form of images, video, sounds, and/or text (referred to herein as "content") to and through Streamate's systems for re-broadcast. All content uploaded to the systems by Performer/Studio shall be works made for hire under the United States Copyright Act, as amended, to the extent eligible; otherwise, Performer/Studio hereby assigns all rights, title and interests in such content to Streamate. Streamate shall then own all such content, and Streamate will have the sole discretion to use any such content in any way it so chooses, including but not limited to in any medium and in any promotion, distribution, advertising, sales and marketing efforts, both during and after the term of this Agreement.</p>
                            <p>Performer/Studio covenants and agrees that Performer/Studio shall not directly or indirectly bring any action or claim against Streamate, its related entities, successors and assigns for trademark, service mark or trade dress infringement. Performer/Studio grants to Streamate, its related entities, successors and assigns the perpetual, irrevocable, fully paid, royalty-free, universal and unconditional right to use, portray, publish, copy, distribute, and display Performer/Studio's identity, name, fictional names (if any), voice, signature, photograph, words, images, personality or other likeness, in whole or in part, for advertising, distribution, marketing, promotion, publicity, and sales purposes. Performer/Studio warrants that any content that Performer/Studio delivers via Streamate's systems will not cause any damage to Streamate's systems and will not violate any applicable laws, rules, regulations or public policies that may govern the content so delivered.</p>
                        </li>
                        <li>
                            <p>Confidentiality And Non-Disclosure</p>
                            <p>Performer/Studio agrees that the terms of this Agreement and any information related to the Streamate web interface, systems, or business (including but not limited to software, business and marketing plans of Streamate) is confidential and proprietary in nature. Performer/Studio shall not directly or indirectly disclose or grant access to such terms or information to any third parties without the prior written permission of Streamate in each instance.</p>
                        </li>
                        <li>
                            <p>Disclaimer - Limitation of liability – Remedies</p>
                            <p>STREAMATE PROVIDES ITS WEB INTERFACE, ANY TECHNOLOGY, WEBSITE AND SYSTEMS, AND ANY INSTRUCTIONS OR ACCESS TO THE SAME, ON AN "AS-IS" BASIS, WITH NO GUARANTEE OF COMPLETENESS, ACCURACY, TIMELINESS, OR OF THE RESULTS OBTAINED FROM ITS OR THEIR USE. STREAMATE ALSO DISCLAIMS AND MAKES NO WARRANTY OR INDEMNITY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTY OF PERFORMANCE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, OR ANY OTHER EXPRESS OR IMPLIED WARRANTY OF ANY KIND WHATSOEVER. UNDER NO CIRCUMSTANCES WILL STREAMATE BE LIABLE TO PERFORMER/STUDIO OR ANY THIRD PARTY FOR ANY UNFORESEEABLE OR UNINTENTIONAL TORTS OR BREACHES OF THIS AGREEMENT ARISING OUT OF ITS PERFORMANCE OF THIS AGREEMENT. ADDITIONALLY, UNDER NO CIRCUMSTANCES WILL STREAMATE BE LIABLE TO PERFORMER/STUDIO OR ANY THIRD PARTY FOR ANY CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, LOST PROFITS, OR OTHER DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. FURTHER, THE PARTIES AGREE THAT STREAMATE'S AGGREGATE LIABILITY TO PERFORMER/STUDIO IN ANY WAY RELATED TO THIS AGREEMENT OR THE SUBJECT MATTERS INVOLVED IN THIS AGREEMENT (REGARDLESS OF WHETHER SUCH LIABILITY MAY ARISE OR BE BASED ON A CONTRACT THEORY OR CAUSE OF ACTION, A TORT THEORY OR CAUSE OF ACTION, OR ANY OTHER TYPE OF THEORY OR CAUSE OF ACTION) SHALL NOT EXCEED ANY MONIES PAID BY STREAMATE TO PERFORMER/STUDIO UNDER THE TERMS OF THIS AGREEMENT.</p>
                            <p>To the maximum extent permitted by law, Performer/Studio hereby releases Streamate and its related entities, successors, and assigns from any liability whatsoever, and hereby waives any and all claims or causes of action of any type against Streamate or any of its related entities, successors, or assigns for any liability, claim, cost, injury, loss, or damage of any kind arising out of or in connection with the subject matter of this Agreement or Performer/Studio's relationship with Streamate. These include but are not limited to any claim, cost, injury, loss, or damage related to personal injuries, death, damage to or destruction of property, rights of publicity or privacy, defamation or portrayal in a false light, whether under a theory of contact, warranty, tort (including negligence, whether active, passive, or imputed), strict liability, product liability, contribution or any other theory.</p>
                            <p>Streamate reserves the right to seek all remedies available at law and in equity for any damage to Streamate or its related entities, successors and assigns or to Streamate's systems caused by any action or breach of this Agreement by Performer/Studio, including but not limited to misrepresentations by Performer/Studio regarding age, eligibility or availability. Also, Streamate reserves the right to block Performer/Studio's access to any Streamate website, including but not limited to from a particular internet address to any Streamate website.</p>
                        </li>
                        <li>
                            <p>Indemnification</p>
                            <p>Performer/Studio agrees to hold harmless, indemnify and defend Streamate and its related entities, successors, and assigns from and against any claims or causes of action of any kind whatsoever brought by any other entity directly or indirectly in any lawsuit or other legal or administrative proceeding or action (including any civil, criminal, or other proceeding or action) that may in any way arise out of or be related to Performer/Studio's breach or violation of any term or condition of this Agreement, to Performer/Studio's performance of this Agreement, or to Performer/Studio's other actions in any way relating to any subject matter of this Agreement.</p>
                        </li>
                        <li>
                            <p>Amendments/Modifications Of Agreement</p>
                            <p>The terms and conditions of this Agreement may be amended or modified by Streamate at the sole discretion of Streamate without notice to Performer/Studio. Any such amendment or modification will occur by Streamate placing the amended or modified version of this Agreement on this website.</p>
                        </li>
                        <li>
                            <p>General Terms</p>
                            <ul>
                                <li>
                                    <p>ENTIRE UNDERSTANDING.</p>
                                    <p>The language of this Agreement constitutes the entire agreement between the parties with respect to the subject matter of this Agreement and supersedes all other agreements, whether written or oral, between the parties.</p>
                                </li>
                                <li>
                                    <p>NOT CONSTRUED AGAINST DRAFTER.</p>
                                    <p>This Agreement shall be construed without any presumption or rule requiring that it be construed against the party which drafted this Agreement.</p>
                                </li>
                                <li>
                                    <p>SUCCESSORS/ASSIGNABILITY.</p>
                                    <p>This Agreement shall be binding and inure to the benefit of the parties, and their respective successors, heirs and permitted assigns. The rights and obligations of Streamate set forth in this Agreement are fully assignable and transferable by Streamate to any corporation, partnership, limited liability company, or other entity, including but not limited to any third-party purchaser of or successor in interest to the assets of Streamate. Performer/Studio may not, under any circumstances, transfer or assign any of Performer/Studio's rights and obligations under this Agreement.</p>
                                </li>
                                <li>
                                    <p>SEVERABILITY – WAIVER.</p>
                                    <p>Each provision of this Agreement is intended by the parties to be enforced to the fullest extent allowed by law. In the event any provision of this Agreement shall be held invalid, illegal or unenforceable, such provision shall be enforced to the maximum extent permitted by law, keeping in mind the intents and purposes of this Agreement, and the remaining provisions shall remain in effect and be binding upon the parties, keeping in mind the intents and purposes of this Agreement.</p>
                                </li>
                                <li>
                                    <p>WAIVER.</p>
                                    <p>Streamate may, at its sole and absolute discretion, waive any breach or failure to perform a term or condition of this Agreement by Performer/Studio in any instance and for any period of time Streamate determines appropriate. Such a waiver by Streamate does not expressly or impliedly mean that any such future breach or failure by Performer/Studio is or may be waived by Streamate. Additionally, if Streamate waives any such breach or failure by one Performer/Studio, then that does not mean Streamate has any duty to or will waive any similar such breach or failure by another Performer/Studio.</p>
                                </li>
                                <li>
                                    <p>STREAMATE'S RELATED ENTITIES.</p>
                                    <p>Any reference in this Agreement to Streamate's "related entities" shall include reference to Streamate's subsidiary companies, parent company, related companies, officers, directors, employees, agents, affiliates, other representatives, and other associated entities.</p>
                                </li>
                                <li>
                                    <p>DISPUTES.</p>
                                    <p>This Agreement shall be governed by, construed and enforced in accordance with the internal laws of the State of Washington, without giving effect to principles and provisions thereof relating to conflict or choice of laws. Venue for any action under this Agreement shall be exclusively in the Washington State Superior Court for King County or the United States District Court for the Western District of Washington at Seattle, Washington. The parties consent to the jurisdictions of such courts and agree not to commence suit in any other jurisdiction or venue. The parties hereby consent to personal jurisdiction over them by such courts, and the parties waive all objections and challenges to such venue and personal jurisdiction.</p>
                                </li>
                                <li>
                                    <p>ATTORNEY FEES.</p>
                                    <p>If any lawsuit or other legal proceeding is commenced to enforce or interpret the provisions of this Agreement, the substantially prevailing party, as designated by the court or other competent authority in such proceeding, shall be entitled to recover (in addition to other damages and relief) its reasonable attorneys fees and costs.</p>
                                </li>
                                <li>
                                    <p>INFORMED CONSENT.</p>
                                    <p>Performer/Studio acknowledges and agrees that Performer/Studio has read, understands, and approves of each term and condition of this Agreement, and that Performer/Studio has had an opportunity to consult with legal counsel and with such other experts or advisors as necessary in connection with this Agreement. Based on this, Performer/Studio voluntarily enters into this Agreement for valid consideration and without any improper inducement, while knowing that this Agreement is binding upon Performer/Studio's proper submission of this signed Agreement and all required information and documentation and Streamate's review and approval of Performer/Studio's submission, without any counter-signature by Streamate of this Agreement.</p>
                                </li>
                            </ul>
                        </li>
                    </ol>
                    <p>Signature</p>
                    <p>You have already signed and acknowledged this agreement previously. By clicking "accept" below you are acknowledging that you have read and agree to the new version of the Performer/Studio Agreement.</p>
                </div>
            </div>
            <div class="box-content-widget per per2">
                <div class="leftsc">
                    <p>Photo ID and Picture of you with ID<br>
                        We must have the following images on file for each performer who will appear on camera:<br>
                        Photo ID - A clear picture or scan of your photo ID.<br>
                        Picture of you with ID - A closeup picture of you holding the ID next to your face.<br>
                        Any current, unexpired, official government-issued ID with your date of birth, signature, and a picture is acceptable. Examples include:<br>
                        Driver's License<br>
                        Passport<br>
                        Military/Government ID<br>
                        Permanent Resident Cards<br>
                        State/Government ID, Benefit, or Health Care Cards<br>
                        Allowed file types are jpg, jpeg, bmp, pdf, tiff, tif, gif. Images may not exceed 5MB.<br>
                        When you have the required images, look for your name below. If you see an error message, follow the instructions to fix the issue. If your name doesn't appear, click the "Add Esignature" button at the bottom of the page to complete this step.<br>
                        Once your name appears without any errors, you can upload your photos:<br>
                        Click "Choose File" under the Photo ID section and add your Photo ID image.<br>
                        Click "Choose File" under the Picture of you with ID section and add your Picture of you with ID image.<br>
                        Once both files are selected, it will upload them automatically.<br>
                        Once you are finished uploading photos, click the "Done" button.
                    </p>
                    <p>The registered account owner can be an individual or a company, and must also <br>
                        be the payee, and taxable entity (if applicable). <br>
                        <p>SUBMIT BASIC DETAILS FOR VERIFICATION</p>
                </div>
                <div class="rightsec righ2"> <img src="<?=base_url('assets/images/proimg.png')?>" alt=""></div>
                <div class="clear"></div>
                <form class="form-agreement" id="verification-form" method="post" autocomplete="off">
                    <div class="form-control">
                        <h4>PERSONAL DETAILS </h4>
                        <div class="indu">
                            <input type="radio" id="radio01" name="i_am_a" checked value="individual" />
                            <label for="radio01"><span></span>I am an individual</label>
                            <input type="radio" id="radio02" name="i_am_a" value="business" />
                            <label for="radio02"><span></span>I am a business</label>
                        </div>
                    </div>
                    <div class="form-widget perso">
                        <div class="form-two-col">
                            <div class="form-group">
                                <input type="text" placeholder="Full Name" value="<?=$user[0]['name']?>" class="man form-control username requiredCheck restrictSpecial" name="verify_full_name" id="verify_full_name" id="verify_full_name" data-check="Full Name" />
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Email Address" value="<?=$user[0]['email']?>" class="com form-control username requiredCheck" name="verify_email" id="verify_email" data-check="Email" />
                            </div>
                        </div>
                        <div class="form-two-col">
                            <div class="form-group">
                                <input type="text" placeholder="BIRTHDAY (YYYY-MM-DD)" value="<?=$user[0]['dob']?>" class="man form-control username requiredCheck" name="verify_dob" onkeypress="return isNumber(this.event)" id="verify_dob" data-check="Birthday" />
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Mobile" value="<?=$user[0]['phone_no']?>" class="mob form-control username requiredCheck" name="verify_phone" id="verify_phone" data-check="Phone" />
                            </div>
                        </div>
                        <div class="form-two-col">
                            <div class="form-group">
                                <input type="text" placeholder="Address Line 1" value="<?=$user[0]['address_one']?>" class="man form-control username requiredCheck" name="verify_add_one" id="verify_add_one" data-check="Address One" />
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Address Line 2" value="<?=$user[0]['address_two']?>" class="man form-control username" name="verify_add_two" id="verify_add_two" />
                            </div>
                        </div>
                        <div class="form-two-col">
                            <div class="form-group">
                                <input type="text" placeholder="City" value="<?=$user[0]['city']?>" class="com form-control username requiredCheck restrictSpecial" name="verify_city" id="verify_city" data-check="City" />
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Postcode" value="<?=$user[0]['pincode']?>" class="com form-control username requiredCheck" name="verify_pincode" id="verify_pincode" data-check="Postcode" onkeypress="return isNumber(this.event)" />
                            </div>
                        </div>
                        <!--<div class="form-two-col">
                            <div class="form-group">
                                <input type="password" value="Password" class="pass form-control username" />
                            </div>
                            <div class="form-group">
                                <input type="password" value="Co" class="pass form-control username" />
                            </div>
                        </div>-->
                        <div class="form-two-col">
                            <div class="form-group">
                                <select class="custom-select requiredCheck" name="verify_country" id="verify_country" data-check="Country">
                                    <option value="">Country</option>
                                    <?php foreach($countries as $countris){ ?>
                                    <option value="<?=$countris->name?>" <?php if($user[0]['country'] == $countris->name){ print 'selected'; } ?>><?=$countris->name?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="form-group red">
                                <div class="indu smalrd">
                                    <input type="radio" id="radio03" name="us_citizen" value="Yes" checked />
                                    <label for="radio03"><span></span>Yes, I am a U.S. citizen</label>
                                    <div class="clear"></div>
                                    <input type="radio" id="radio04" name="us_citizen" value="No" />
                                    <label for="radio04"><span></span>No, I am NOT a U.S. citizen</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-control use">
                            <h3><span>X</span>Address Verification Needed</h3>
                            <p>Under penalties of perjury, I declare that I have examined the information on this form and to the best of my knowledge and belief it is true, correct, and complete. I further certify under penalties of perjury that:</p>
                            <p>I am the individual that is the beneficial owner (or am authorized to sign for the individual that is the beneficial owner) of all the income to which this form relates or am using this form to document myself for chapter 4 purposes,</p>
                            <p>The person name on line 1 of this not a U.S. person,</p>
                            <p>The income to which this form relates is: (a) not effectively connect with the conduct of a trade or business in the United States, (b) effectively connected but is not subject to tax under an applicable income tax treat, or (c) the partner's share of a partnership's effectively connected income,</p>
                            <p>The person named on line 1 of this form is a resident of the treaty country listed on line 9 of the form (if any) within the meaning of income tax treaty between the United States and that country, and</p>
                            <p>For broker transactions or barter exchanges, the beneficial owner is an exempt foreign person as defined in the instructions.
                                Furthermore, I authorize this form to be provided to any withholding agent that has control, receipt, or custody of the income of which I am the beneficial owner or any withholding agent that can be disbursed or make payments of the income of which I am the beneficial owner. I agree that I will submit a new form within 30 days if any certification made on this form becomes incorrect.</p>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="form-widget">
                        <div class="form-two-col brss">
                            <div class="form-group">
                                <label>UPLOAD PHOTO ID</label>
                                <input type="file" class="form-control username formsm requiredCheck" id="verify_pic" name="verify_pic" data-check="Photo ID" />
                                <div class="brows verify_pic_ref">BROWSER</div>
                            </div>
                            <div class="form-group">
                                <label>UPLOAD PHOTO OF YOU WITH ID</label>
                                <input type="file" class="form-control username formsm requiredCheck" id="verify_pic_id" name="verify_pic_id" data-check="Photo of you with ID" />
                                <div class="brows verify_pic_id_ref">BROWSER</div>
                            </div>
                            <!--<div class="form-group">
    <label>+ ADD ANOTHER PERFORMER</label>
    <input type="text" value="E-SIGNATURE" class="form-control username formsm" />
    <div class="brows">BROWSER</div>
</div>-->
                        </div>
                        <div class="form-two-col"></div>
                    </div>
            </div>
            <div class="box-content-widget">
                <h2>Sign Agreement</h2>
                <div class="form-group">
                    <div class="inline-items">
                        <input type="text" placeholder="Full Legal Name" class="form-control requiredCheck restrictSpecial" id="verify_name" name="verify_name" data-check="Full Legal Name">
                        <input type="text" placeholder="Day (DD)" class="form-control day requiredCheck" id="verify_day" name="verify_day" onkeypress="return isNumber(this.event)" data-check="Day">
                        <input type="text" placeholder="Month (MM)" class="form-control month requiredCheck" id="verify_month" name="verify_month" onkeypress="return isNumber(this.event)" data-check="Month">
                        <input type="text" placeholder="Year (YYYY)" class="form-control year requiredCheck" id="verify_year" name="verify_year" onkeypress="return isNumber(this.event)" data-check="Year">
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <label class="check">I HAVE READ AND AGREE TO THE TERMS
                            <input type="checkbox" id="veriry_agreement">
                            <span class="checkmark"></span>
                        </label>
                    </div>
                </div>
                <!--<div class="form-group">
    <div class="inline-items">
        <input type="password" placeholder="*********" class="form-control password" />
        <div class="upload-btn-wrapper">
            <button class="btn">Browse</button>
            <input type="file" name="myfile" />
        </div>
    </div>
</div>-->
                <div class="form-action">
                    <input type="submit" value="Submit" id="verify_submit_btn" disabled />
                </div>
                <div style="text-align:center;">
                    <span class="verification-message" style="color:red;font-style: italic;"></span>
                </div>
            </div>
            </form>
        </div>
    </section>
</main>
</section>
